### ISSUE TITLE
AI Agents Support Dynamic Instructions

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#1019]
## Benefits

- **Data Integration**: Ability to embed various types of data such as environment variables, command outputs, and agent variables.
- **Reduced Function Calls**: The pre-call mechanism streamlines function execution by minimizing the number of calls made to the main function.
- **User Interaction**: Interact with users to generate different instructions based on their choices, prompting them for specific information that enhances the response.

## Implementation

To enable dynamic instructions for AI agents, two key modifications are required:

1. **Modify the `index.yaml` File**: 
   - Add `dynamic_instructions: true` configuration item. This triggers the agent to dynamically generate instructions at runtime.

2. **Update the Tools Script**: 
   - Incorporate the `_instructions` function into the tools script. This function will be responsible for generating the necessary dynamic instructions when called.

AIChat will load `index.yaml` and check if the `dynamic_instructions` field is set to `true`. If it is true, it will execute `<agent-name> _instructions` and return its value as `instructions`.

## Conclusion

We welcome any suggestions or feedback to further improve the implementation and functionality of dynamic instructions for AI agents.

**Comment by cboecking** [comment]
Thank you! Are there a couple of use cases this scenario solves or provides support that is not possible today?

**Comment by einarpersson** [comment]
> Thank you! Are there a couple of use cases this scenario solves or provides support that is not possible today?

I wanted this feature so much that I [created a wrapper script](https://github.com/sigoden/aichat/pull/1023#issuecomment-2512683955). I don't know if any radically new things are enabled, but it has been a game changer in practicallity. Now I can add arbritary context to my shell assistant for example.

I would say it has two main benefits
1. It increases reliability a lot since the assistant has relevant context a priori, so that it does not make stupid assumptions and then fail and then has to course correct
2. It makes things faster since it does not have to make a roundtrip to a llm to figure out basic things
