### ISSUE TITLE
Allow configuring a default role

### ISSUE THREAD

**Issue by evanrelf** [sigoden/aichat#220]
**Is your feature request related to a problem? Please describe.**
By default, OpenAI's GPT models are very chatty, which means more tokens, which means responses take longer and cost more money.

You can already choose a role - e.g. a "terse" role that instructs the model to be brief unless asked to elaborate - but you can't choose a _default_ role when `aichat` starts.

**Describe the solution you'd like**
A `role` option in `config.yaml` to pick the default role. Would behave similarly to how the `model` option sets a default model, and corresponds with the `--model` CLI option.

**Describe alternatives you've considered**
Shell aliases are the only alternative I can think of.

**Additional context**
_n/a_

**Comment by Pizmovc** [comment]
Is there a way to specify a default role for usage via CLI?

I thought the `prelude` option will affect both, but it only affects the REPL environment.

**Comment by sigoden** [comment]
No intention of supporting two prelude.
Here’s why:
1. You can use shell alias to achieve what you want.
2. No one else has mentioned it for so long, indicating whether it is a niche demand. 

@Pizmovc

**Comment by Pizmovc** [comment]
If there is no easy way of reusing the prelude in the CLI I think your suggestion makes sense.

Though if I'm using the alias with a role (`alias ai="aichat -r my-default-role"`) as my default interface for `aichat`, it sucks that I cant override the role by passing it a second time, since I get an error:
```
❯ ai -r emoji "bread"
error: the argument '--role <ROLE>' cannot be used multiple times

Usage: aichat [OPTIONS] [TEXT]...

For more information, try '--help'.
```

I would need a second alias or use the original `aichat` command for when a different role is needed.

Anyway, thank you for your time and for considering this in the first place 🙇
