### ISSUE TITLE
Streaming Mode has Stopped Working with in Command Mode

### ISSUE THREAD

**Issue by madnight** [sigoden/aichat#221]
When I use AI Chat from the terminal, for example `aichat -r shell unzip a file` or `$(echo "$data" | aichat -S -H to json)` , the streaming mode has stopped working in version 0.9.0.

However, the streaming mode still works in the REPL mode.

In 0.8.0, the streaming mode worked for both REPL and command mode.

**Comment by sigoden** [comment]
In command mode, aichat still rendering in streaming.

In REPL, The text is rendered letter by letter. Under the command line, it is rendered sentence by sentence. This is a necessary design.

REPL supports redrawing, while command mode does not. 
AIChat must collect a complete sentence in order to enable syntax highlighting, text wrapping, then rendering.
