### ISSUE TITLE
Support streaming to pipe

### ISSUE THREAD

**Issue by johnd0e** [sigoden/aichat#414]
**Describe the bug**
When using in terminal text streaming works as it should, but when piping output - it shows up all at once.

**To Reproduce**
```
aichat tell me a story|less
```

**Expected behavior**
When I pipe other utilities to `less` - I see output appear line by line.

**Environment (please complete the following information):**
- os version: Windows 10
- aichat version: 0.16.0 and earlier
- terminal version: N/A

**Comment by sigoden** [comment]
This is not a bug but is designed.

Aichat will detect whether tdout is terminal. If it is not (e.g. used in a script or piped into another application), aichat will automatically switch to non-stream mode.

Why design like this:
- Non-stream mode is faster than stream mode, as there is less data transmission.
- Non-stream mode prints directly, rather than processing markdown and wrap, which is also faster.
- Non-stream mode outputs data once, and you have chance to preprocess the data, such as extracting the code from markdown when using `-c/--code`.

The use cases you have showed so far are not sufficient for me to change this design.

**Comment by johnd0e** [comment]
> The use cases you have showed so far are not sufficient for me to change this design.

That was not usecase, just a sample to reproduce the issue.

My real usecase is calling aichat from my application, where I need streaming.

> If it is not, aichat will automatically switch to non-stream mode.

But there is ` --no-stream` key for cases, when streaming is not needed.
So I do not see real value in automatic switching it off for piping.

Anyway, if you feel that valuable, you could introduce `--stream` key to force streaming for cases such as mine.
