### ISSUE TITLE
Support piping of filenames

### ISSUE THREAD

**Issue by johannesCmayer** [sigoden/aichat#697]
**Is your feature request related to a problem? Please describe.**
I have an obsidian vault. I want to rag all *.md files. However, there are *.excalidraw.md files, and other md files I'd like to exclude. 

**Describe the solution you'd like**
Ideally, I'd like to just use a command like `find` to select all the correct files and then pipe it into aichat. 

**Describe alternatives you've considered**
Alternatively, I it would also be good if you could specify a file where each line is a path.

**Additional context**
Right now this does not work at all actually. There are so many files that it takes many minutes to just paste them at the interactive prompt. Even if I just select the correct directories it does not work. For some reason, I get:
```
...
Load  [82/82]
Error: Permission denied (os error 13)
```
After all the files have been loaded.

**Comment by sigoden** [comment]
I tend not to support this feature.

When aichat receives a pipe, it uses it as the message text. This works well and I'm not planning on changing it, because it would be ambiguous or make the cli options too redundant.

`add_documents` can load complex document paths.

![image](https://github.com/sigoden/aichat/assets/4012553/ca1587f5-a00c-4575-bf91-6a1d8de177ae)

If you confirm that there is a problem with aichat `add_document`, please submit a new issue.
