### ISSUE TITLE
Respect XDG base directory (~/.config)

### ISSUE THREAD

**Issue by nounderline** [sigoden/aichat#769]
Since this is terminal-first app, it would make sense to put config files in location expected by many terminal users by following [XDG base directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

Right now, on macOS, config is stored under `~/Library/Application Support/`. Instead, by default, they should be stored in `~/.config/` as per spec. On the other hang, data files such rags and session should be stored separate directory, ie. `.local/state` to make config easier to transfer across workstations.

**Comment by sigoden** [comment]
I disagree with you.

Many modern Go/Rust CLI applications place their configuration files in `~/Library/Application Support/`.
- https://docs.rs/dirs/latest/dirs/fn.config_dir.html
- https://pkg.go.dev/os#UserConfigDir

Placing everything in the same directory is more intuitive and user-friendly.

**Comment by nounderline** [comment]
fwiw, aichat is the first cli that I've used that is using lib-default `~/Library/Application Support`. iterm2, nvim, raycast, wireshark, zed, tmux, direnv, terraform (written in Go), lazygit (also written in Go) are using `~/.config` to stay compatible with Linux.

Anyways, here's a script to use `~/.config` in aichat for anyone interested:

```sh
#!/bin/sh

export AICHAT_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/aichat

exec aichat $@
```

**Comment by hkrutzer** [comment]
I don't think it is intuitive, this is the first tool I have had to configure in this folder. It has also caused issues for me with `argc install` because it tried to install to `~/Library/Application`. 

It does seem there are other tools that also use the `Application Support` directory, e.g.: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md but this tool does use `$XDG_CONFIG_HOME` if it is defined. If you search for `$XDG_CONFIG_HOME` on Github it looks like many tools use `$XDG_CONFIG_HOME` if it is defined, such as https://github.com/asciinema/asciinema/blob/f2c4359603f2a0cb710cd6bf415b857fb5895455/src/config.rs#L303 and https://github.com/pier-cli/pier/blob/0ea5a82a9c22f69d6d429397071f2a5fd7742d2f/src/cli.rs#L112-L126. It seems to me aichat should also respect `$XDG_CONFIG_HOME` if it is set on macos.

**Comment by unphased** [comment]
Thanks for fixing this 3 weeks ago. i set up aichat a few months back. i was never gonna be able to find this file again until i found this issue. thank you for revealing the old config lives in application support.
