### ISSUE TITLE
Integration of fabric patterns

### ISSUE THREAD

**Issue by eugeis** [sigoden/aichat#784]
Hello,

thank you for really great product.

I am using fabric, especially fabric patterns / prompts (https://github.com/danielmiessler/fabric/tree/main/patterns), but I like Aichat much more and would like to use those patterns/prompts with Aichat. 

What do you think about integration of those patterns into Aichat?

**Comment by cboecking** [comment]
Hi, how do you currently (manually) these patterns? 

For example:
aichat -f some-prompt/system.md -f some-prompt/user.md -f some-other-material-to-be-reviewed.txt

How would you propose aichat better take advantage? Here are my thoughts:
- have system variable that knows where to look for the patterns (how to point aichat to the directory)
- have aichat auto complete finding the right prompt directory (example: improve_writing vs rate_ai_response vs ...)
- have aichat automatically look for both filename conventions (system.md and user.md) and add them automagically

What I like about this concept is that it is not specific to just fabric. I can me used by any organization's collection of prompts.

Since aichat already passes in the file name (in addition to the content), the submitted message will have that much more context (system.md vs user.md) automagically.

Chuck

**Comment by eugeis** [comment]
Hi, 
thank you for quick response!

I see it same way, it is better to be independent of of fabric.
Those 3 points would be perfect.

Could I support some how?

**Comment by cboecking** [comment]
Hi @eugeis - we will need to wait for @sigoden to comment. I just offered my additional thoughts because I liked your suggestion. Chuck

**Comment by sigoden** [comment]
We will not support this feature. 

AIChat already supports `roles.yaml` and `--prompt/.prompt`, which is sufficient to meet all needs.

There are two ways to use fabric patterns:

- convert the system.md files to roles.yaml (recommand)

- use `--prompt`
```
aichat --prompt "$(< path-to-system.md)" 
```

**Comment by cboecking** [comment]
Confirmed. I feel like this is a worthy topic on your FAQ.

**Comment by eugeis** [comment]
ok, thanks for clarification.
