### ISSUE TITLE
Should we strip `%` wrapper from role names?

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#849]
In AIChat, we wrap built-in role names with `%` to indicate they are built-in.

The question is, do users really care whether they are built-in or not?  In scenarios without auto-completions, users may not know whether a role is built-in and may hesitate to use `%` to wrap the role name.

if we eventually decide to strip the `%`, the  role names in `aichat --list-roles` and `.role <tab>`  will no longer have `%`:
```
%shell% -> shell
%explain-shell% -> explain-shell
%code% => code
%functions% => functions
```

**Note that even if we eventually decide to strip the `%`, we will maintain backward compatibility with `%<name>%`. For example, `aichat -r %functions%` can still work.**

What do you think? Any suggestions or feedback is helpful.

**Comment by cboecking** [comment]
Great question. Here are my thoughts:

* Having the auto-complete of all default available roles (beginning  with %) is nice and convenient.
* The only time I find value in the training % is when you are performing context substitution.

Regarding context substitution, If I had a script that had the following command,  It would use the assigned role by default. Because the role is surrounded with %, I could easily substitute a customized role if/when needed using the linux sed command.

```bash
cat somefile | aichat -r %some-default-role% | cmd-write-database
```

There is a reasonable value for having a default role that can be easily/programmatically changed.

My 2 cents... Chuck

**Comment by justinlovinger** [comment]
I definitely like being able to easily tell if a role is built-in, and I do not mind typing `%` when completion is not available.

**Comment by sigoden** [comment]
Conclusion: No changes will be made; we will keep it as is.

Thank you all for your participation.
