### ISSUE TITLE
Do not save empty session

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#942]
Hi,

My primary need is to be able to exit a session without saving it. But I want to keep the setting that save the session on exit by default which I find good. So, my "path" to do it is to clear the session before the exit. But in this case, aichat save an empty session.
Shouldn't it exit without saving it here?

**Comment by sigoden** [comment]
@dtrckd 
Sorry, I can't understand what you're trying to express.

> able to exit a session without saving it
> keep the setting that save the session on exit by default

 Aren't these two paragraphs conflicting?

If you want to exit a session without saving it, you should `.set save_session false`.
If you want to save the session on exit by default, you should `.set save_session true`.

If the session has `save_session` set to true, It will save everything as it is when you exit.

Since you cleared the messages (`.empty session`) before exiting, the saved session will naturally contain empty messages. 
However, the session will never truly be empty; it may have content like the following:

```
model: openai:gpt-4o-mini
save_session: true
messages: []
```

The above can be confirmed in the last-commit version of AIChat.

**Comment by dtrckd** [comment]
> Aren't these two paragraphs conflicting?

You're right, I should have added "without saving it **if it is empty**". By empty I meant what you wrote; A session with no message.

I don't understand the point of saving these sessions with no messages, plus it wastes time when tidying up your "unnamed/temp" sessions. Who would use these empty, unnamed sessions?

**Comment by sigoden** [comment]
@dtrckd 

Even if the session has no messages, it has some configuration fileds worth saving.

For example,
```
model:
tempearture:
top_p:
use_tools:
save_session:
compress_threshold
role_name:
```

**Comment by dtrckd** [comment]
OK. I'll default `save_session` to false to prevent unwanted file, to me, to accumulate. However, if a session is explicitly saved using `.save session my-session`, could aichat automatically set `save_session` to true?

This will save on a couple of require user action and prevent messages loss if we forget to set it.

**Comment by sigoden** [comment]
> if a session is explicitly saved using `.save session my-session`, could aichat automatically set `save_session` to true?

No. `.save session` simply saves as is.
